name: Build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Download dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libwebkit2gtk-4.0-dev

    - name: Build
      run: |
        export GO111MODULE=on
        go build -v -mod=vendor
    
    - name: Run Tests
      run: |
        go fmt ./...
        go vet ./...